### ISSUE TITLE
Incidencia - API - Error en UpdateModel al incluir usuarios sin contraseña

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaDA#242]
Al ejecutar la función updateModel, se produce un error cuando los usuarios no administradores no tienen contraseña asignada. El error parece originarse en el archivo CleanModel.ts, específicamente cuando se intenta acceder a propiedades que no están definidas, resultando en un TypeError.

```
node_sda       | Error : TypeError: Cannot read properties of undefined (reading 'table')
node_sda       |     at /sda/app/eda/eda_api/dist/module/updateModel/service/cleanModel.js:64:34
node_sda       |     at Array.find (<anonymous>)
node_sda       |     at CleanModel.<anonymous> (/sda/app/eda/eda_api/dist/module/updateModel/service/cleanModel.js:62:53)
```

Este error ocurre debido a una propiedad undefined en `CleanModel.ts,`

**Comment by jortilles** [comment]
Se crea el pr https://github.com/SinergiaTIC/SinergiaDA/pull/244
